site_name: National 4 Computer Science
nav:
    - Home: 'index.md'
    - Unit 1 - Software Design and Development:
      - 01-SDD/index.md
      - Program Design:     
          - Flowcharts: '01-SDD/1.1-Flowcharts.md'
      - Software Implementation:
          - Input and Output: '01-SDD/1.2-Input-and-Output.md'
          - Variables and Data Types: '01-SDD/1.3-Variables-and-Data-Types.md'
          - Simple Conditional Statements: '01-SDD/1.4-Simple-Conditional-Statements.md'
          - Fixed Loops (for): '01-SDD/1.5-Fixed-Loops-(for).md'
          - Conditional Loops (while): '01-SDD/1.6-Conditional-Loops-(while).md'
      - Testing:      
          - Normal, Extreme and Exceptional Test Data: '01-SDD/1.8-Normal-Extreme-and-Exceptional-Test-Data.md'
      - Evaluation:
          - Readability: '01-SDD/1.9-Readability.md'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - def_list
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
theme:
  name: material
  font:
    text: Quicksand
  palette: 
    - scheme: slate
      toggle:
       icon: material/weather-sunny
       name: Dark mode
      primary: green
      accent: deep purple

    - scheme: default
      toggle:
       icon: material/weather-night
       name: Light mode
      primary: blue
      accent: deep orange
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left
  features:
    - content.code.copy
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.indexes 

